apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
  labels:
   {{- include "redpanda.labels" . | nindent 4 }} 
data:
  redpanda.yaml: |
    config_file: {{ .Values.config.config_file }}
    license_key: {{ .Values.config.license_key }}
    organization: {{ .Values.config.organization }}
    redpanda:
{{ toYaml .Values.config.redpanda | indent 6 }}
      seed_servers:
        {{- $envAll := . }}
        {{- range untilStep 0 (.Values.replicaCount|int) 1 }}
        - node_id: {{ . }}
          host:
            address: {{ template "redpanda.name" $envAll }}-{{ . }}.{{ template "redpanda.name" $envAll }}
            port: {{ $envAll.Values.config.redpanda.advertised_rpc_api.port }}
        {{- end }}
    rpk:
{{ toYaml .Values.config.rpk | indent 6 }}
