apiVersion: v1
kind: Service
metadata:
  name: {{ include "redpanda.name" . }}
  labels:
   {{- include "redpanda.labels" . | nindent 4 }} 
spec:
  clusterIP: None
  ports:
    - name: kafka-tcp
      protocol: TCP
      port: {{ .Values.config.redpanda.advertised_kafka_api.port }}
      targetPort: {{ .Values.config.redpanda.advertised_kafka_api.port }}
  selector:
    app: {{ template "redpanda.name" . }}
