apiVersion: v1
kind: Service
metadata:
  name: redpanda-headless
  labels:
    {{- include "redpanda.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "redpanda.selectorLabels" . | nindent 4 }}
