apiVersion: v1
kind: Service
metadata:
  name: {{ template "redpanda.fullname" . }}-0
spec:
  type: ClusterIP # necessary?
  ports:
    - protocol: TCP
      port: 33145
      targetPort: 33145
  selector:
    statefulset.kubernetes.io/pod-name: redpanda-0
