apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  selector:
    matchLabels:
     app: redpanda
  serviceName: "redpanda"
  replicas: 2
  externalTrafficPolicy: Local
  selector:
    matchLabels:
      app: redpanda
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
