apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "redpanda.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "redpanda.name" . }}
  serviceName: {{ template "redpanda.name" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "redpanda.name" . }} 
    spec:
      initContainers:
        - name: {{ template "redpanda.name" . }}-configurator
          image: {{ .Values.image.repository }}
          command: ["/bin/sh", "-c"]
          args:
            - >
              CONFIG=/tmp/config/redpanda.yaml;
              NODE_ID=${HOSTNAME##*-};
              SERVICE_NAME={{ template "redpanda.name" . }}-$NODE_ID;
              cp /tmp/base-config/redpanda.yaml $CONFIG;
              rpk --config $CONFIG config set redpanda.node_id $NODE_ID;
              if [ "$NODE_ID" = "0" ]; then
                rpk --config $CONFIG config set redpanda.seed_servers '[]' --format yaml;
              fi;
              rpk --config $CONFIG config set redpanda.advertised_rpc_api.address $SERVICE_NAME;
              rpk --config $CONFIG config set redpanda.advertised_rpc_api.port {{ .Values.config.redpanda.advertised_rpc_api.port }};
              rpk --config $CONFIG config set redpanda.advertised_kafka_api.address $SERVICE_NAME;
              rpk --config $CONFIG config set redpanda.advertised_kafka_api.port {{ .Values.config.redpanda.advertised_kafka_api.port }};
          volumeMounts:
            - name: base-config 
              mountPath: /tmp/base-config 
            - name: config
              mountPath: /tmp/config
      containers:
        - name: {{ template "redpanda.name" . }}
          image: {{ .Values.image.repository }}
          # command: ["/bin/sh", "-c"]
          args:
           - --config /tmp/config/redpanda.yaml
           - start
           - --
           - --default-log-level={{ .Values.config.seastar.default_log_level }}
          ports:
            - containerPort: {{ .Values.config.redpanda.admin.port }}
              name: admin
            - containerPort: {{ .Values.config.redpanda.advertised_kafka_api.port }}
              name: kafka
            - containerPort: {{ .Values.config.redpanda.advertised_rpc_api.port }}
              name: rpc
          volumeMounts:
            - name: config
              mountPath: /tmp/config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: base-config
          configMap:
            name: base-config
        - name: config
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
