apiVersion: v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: redpanda-0
    statefulset.kubernetes.io/pod-name: redpanda-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
