apiVersion: v1
kind: Service
metadata:
  name: redpanda
  labels:
    app: redpanda
spec:
  clusterIP: None
  ports:
    - name: rpc
      protocol: TCP
      port: 33145
      targetPort: 33145
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    app: redpanda
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-0
spec:
  ports:
    - name: rpc
      protocol: TCP
      port: 33145
      targetPort: 33145
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    statefulset.kubernetes.io/pod-name: redpanda-0
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-1
spec:
  ports:
    - name: rpc
      protocol: TCP
      port: 33145
      targetPort: 33145
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    statefulset.kubernetes.io/pod-name: redpanda-1
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-2
spec:
  ports:
    - name: rpc
      protocol: TCP
      port: 33145
      targetPort: 33145
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
  selector:
    statefulset.kubernetes.io/pod-name: redpanda-2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: base-config
data:
  redpanda.yaml: |
    config_file: /etc/redpanda/redpanda.yaml
    license_key: ""
    node_uuid: mf1PqvLg826mCjiYRRKcBb4MjtL88agNyGajk3GoELmgKixYA
    organization: ""
    redpanda:
      admin:
        address: 0.0.0.0
        port: 9644
      auto_create_topics_enabled: true
      data_directory: /var/lib/redpanda/data
      developer_mode: false
      kafka_api:
        address: 0.0.0.0
        port: 9092
      kafka_api_tls:
        cert_file: ""
        enabled: false
        key_file: ""
        truststore_file: ""
      node_id: 0
      rpc_server:
        address: 0.0.0.0
        port: 33145
      seed_servers:
        - node_id: 0
          host:
            address: redpanda-0
            port: 33145
    rpk:
      coredump_dir: /var/lib/redpanda/coredump
      enable_memory_locking: false
      enable_usage_stats: true
      overprovisioned: false
      tls:
        cert_file: ""
        key_file: ""
        truststore_file: ""
      tune_aio_events: false
      tune_clocksource: false
      tune_coredump: false
      tune_cpu: false
      tune_disk_irq: false
      tune_disk_nomerges: false
      tune_disk_scheduler: false
      tune_fstrim: false
      tune_network: false
      tune_swappiness: false
      tune_transparent_hugepages: false
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  selector:
    matchLabels:
      app: redpanda
  serviceName: "redpanda"
  replicas: 3
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      initContainers:
        - name: redpanda-configurator
          image: vectorized/redpanda
          command: ["/bin/sh", "-c"]
          args:
            - >
              CONFIG=/tmp/config/redpanda.yaml;
              NODE_ID=${HOSTNAME##*-};
              SERVICE_NAME=redpanda-$NODE_ID;
              cp /tmp/base-config/redpanda.yaml $CONFIG;
              rpk --config $CONFIG config set redpanda.node_id $NODE_ID;
              if [ "$NODE_ID" = "0" ]; then
                rpk --config $CONFIG config set redpanda.seed_servers '[]' --format yaml;
              fi;
              rpk --config $CONFIG config set redpanda.advertised_rpc_api.address $SERVICE_NAME;
              rpk --config $CONFIG config set redpanda.advertised_rpc_api.port 33145;
              rpk --config $CONFIG config set redpanda.advertised_kafka_api.address $SERVICE_NAME;
              rpk --config $CONFIG config set redpanda.advertised_kafka_api.port 9092;
              rpk --config $CONFIG config set rpk.smp 1;
          volumeMounts:
            - name: base-config
              mountPath: /tmp/base-config
            - name: config
              mountPath: /tmp/config
      containers:
        - name: redpanda
          image: vectorized/redpanda
          args:
            - --config /tmp/config/redpanda.yaml
            - start
            - --
            - --default-log-level=debug
          ports:
            - containerPort: 9644
              name: admin
            - containerPort: 9092
              name: kafka
            - containerPort: 33145
              name: rpc
          volumeMounts:
            - name: config
              mountPath: /tmp/config
      volumes:
        - name: base-config
          configMap:
            name: base-config
        - name: config
          emptyDir: {}
