apiVersion: v2
name: redpanda
description: Redpanda is the real-time engine for modern apps.
type: application
version: 0.1.0
appVersion: latest
sources:
- https://github.com/vectorizedio/deployment-automation/kubernetes
maintainers:
- name: vectorized
  email: hi@vectorized.io
