# Default values for redpanda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: vectorized/redpanda
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

config:
  config_file: /etc/redpanda/redpanda.yaml
  license_key: ""
  node_uuid: mf1PqvLg826mCjiYRRKcBb4MjtL88agNyGajk3GoELmgKixYA
  organization: ""
  redpanda:
    admin:
      address: 0.0.0.0
      port: 9644
    advertised_kafka_api:
      address: 0.0.0.0
      port: 9092
    advertised_rpc_api:
      address: 0.0.0.0
      port: 33145
    auto_create_topics_enabled: true
    data_directory: /var/lib/redpanda/data
    developer_mode: false
    kafka_api:
      address: 0.0.0.0
      port: 9092
    kafka_api_tls:
      cert_file: ""
      enabled: false
      key_file: ""
      truststore_file: ""
    node_id: 0
    rpc_server:
      address: 0.0.0.0
      port: 33145
  rpk:
    coredump_dir: /var/lib/redpanda/coredump
    enable_memory_locking: false
    enable_usage_stats: true
    overprovisioned: false
    smp: 1
    tls:
      cert_file: ""
      key_file: ""
      truststore_file: ""
    tune_aio_events: false
    tune_clocksource: false
    tune_coredump: false
    tune_cpu: false
    tune_disk_irq: false

volumeMount:
  name: config
  mountPath: /tmp/config 
  base:
    name: base-config
    mountPath: /tmp/base-config

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: 
  requests:
    cpu: 1   # 2
    memory: 3Gi
  limits:
    cpu: 1   # 2
    memory: 6Gi

nodeSelector: {}

tolerations: []

affinity: {}
