apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: redpanda-dev1
  region: us-west-2
  version: "1.18"

iam:
  withOIDC: true

managedNodeGroups:
  - name: redpanda-dev1-nodegroup
    instanceType: m5.large
    minSize: 1
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/vectorized-ec2.pub
